version: '3.8'
services:
  dev-postgres:
    image: postgres:14.4-alpine
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: user1234
      POSTGRES_PASSWORD: password1245
      POSTGRES_DB: go-api-db
    restart: always
    networks:
      - first
networks:
  first:
